class RootFsRequiredPacks:
    PACKAGE_LIST_DISKUTILS = [("addpart", " --help"),
                              ("blockdev", " --help"),
                              ("cfdisk", " --help"),
                              ("delpart", " --help"),
                              ("fdformat", " --help"),
                              ("fdisk", " --help"),
                              ("fsck", " --help"),
                              ("fsck.ext3", " --help"),
                              ("fsck.fat", " --help"),
                              ("fsck.util-linux", " --help"),
                              ("fsck.ext2", " --help"),
                              ("fsck.ext4", " --help"),
                              ("fsck.msdos", " --help"),
                              ("fsck.vfat", " --help"),
                              ("isosize", " --help"),
                              ("mkfs", " --help"),
                              ("mkfs.ext3", " --help"),
                              ("mkfs.fat", " --help"),
                              ("mkfs.ubifs", " --help"),
                              ("mkfs.ext2", " --help"),
                              ("mkfs.ext4", " --help"),
                              ("mkfs.msdos", " --help"),
                              ("mkfs.vfat", " --help"),
                              ("mkswap", " --help"),
                              ("raw", " --help"),
                              ("resizepart", " --help"),
                              ("sfdisk", " --help"),
                              ("swaplabel", " --help")]

    PACKAGE_LIST_E2FSPROGS = [("mkfs.ext4", ""),
                              ("fsck.ext4", ""),
                              ("e2fsck", ""),
                              ("mke2fs", ""),
                              ("debugfs", " -h"),
                              ("dumpe2fs", ""),
                              ("tune2fs", "")]

    PACKAGE_LIST_PROCPS = [("ps", " --help"),
                           ("top", " --help"),
                           ("vmstat", " --help"),
                           ("w", " --help"),
                           ("kill", " --help"),
                           ("free", " --help"),
                           ("slabtop", " --help"),
                           ("skill", " --help")]

    PACKAGE_LIST_DOSFSTOOLS = [("dosfsck", ""),
                               ("fsck.msdos", ""),
                               ("fsck.vfat", ""),
                               ("mkdosfs", ""),
                               ("mkfs.msdos", ""),
                               ("mkfs.vfat", ""),
                               ("dosfslabel", "")]

    REQUIRED_FONTS = [r"DejaVu.+\.ttf",
                      r"NotoSans-.+\.ttf",
                      r"NotoSansCJKjp.+\.otf",
                      r"NotoSansCJKkr.+\.otf",
                      r"NotoSansCJKsc.+\.otf",
                      r"NotoSansCJKtc.+\.otf"]
